WebMVC5/Controllers/usuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using model.entity;
using model.negocio;

namespace WebMVC5.Controllers
{
    public class usuarioController : Controller
    {
        private usuarioNego objUsuarioNeg;
        public usuarioController()
        {
            objUsuarioNeg = new usuarioNego();
        }
        // GET: usuario
        public ActionResult Inicio()
        {
            List<usuario> lista=objUsuarioNeg.findAll();
            return View(lista);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(usuario objUsuario)
        {
            mensajeInicio();
            objUsuarioNeg.create(objUsuario);
            mensajeErrorRegistro(objUsuario);
            return View();
        }
        //metodo edit
        [HttpPost]
        public ActionResult Update(usuario objUsuario)
        {
            objUsuarioNeg.update(objUsuario);
            mensajeErrorRegistro(objUsuario);
            return View();
        }
        public void mensajeInicio()
        {
            ViewBag.mensajeInicio = "Formulario de Registro de Usuarios";
        }
        public void mensajeErrorRegistro(usuario objUsuario)
        {
            switch (objUsuario.Estado)
            {
                case 10:
                    ViewBag.mensajeError = "Campo codigo esta vacio";
                    break;
                case 1:
                    ViewBag.mensajeError = "Excedio la longitud de la cadena,caracteres de tipo numero";
                    break;
                case 100:
                    ViewBag.mensajeError = "solo se permiten numeros";
                    break;
                case 20:
                    ViewBag.mensajeError = "Campo nombre esta vacio";
                    break;
                case 2:
                    ViewBag.mensajeError = "longitud de la cadena excedio,solo se permite menor o igual que 50";
                    break;
                case 30:
                    ViewBag.mensajeError = "Campo apellido esta vacio";
                    break;
                case 3:
                    ViewBag.mensajeError = "campo apellido longitud de la cadena excedio,solo se permite menor o igual que 50";
                    break;
                case 40:
                    ViewBag.mensajeError = "Campo telefono esta vacio";
                    break;
                case 4:
                    ViewBag.mensajeError = "campo telefono longitud de la cadena excedio,solo se permite menor o igual que 12";
                    break;
                case 5:
                    ViewBag.mensajeError = "Usuario ["+objUsuario.Id_user +"] ya esta registrado";
                    break;
                case 99:
                    ViewBag.mensajeExito = "Usuario [" + objUsuario.Id_user + "] se registro correctamente";
                    break;
            }
        
        }
    }
}

WebMVC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Inicio", "usuario", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WebMVC5/Views/usuario/Create.cshtml
@model model.entity.usuario
@{
    ViewBag.Title = "Create";
}
<div>
   <h1>@ViewBag.mensajeInicio</h1> 
</div>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Id_user,htmlAttributes:new { @class="control-label col-md-2"})
            <div class="col-md-6">
                @Html.EditorFor(model => model.Id_user, new { htmlAttributes=new {@class="form-control" }})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-actions col-md-offset-2">
            <input class="btn btn-primary" type="submit"name="btnGuardar" value="Guardar" />
            @Html.ActionLink("Regresar al Listado","Inicio")

        </div>
    </div>
}
<div>
    @ViewBag.mensajeError
   
</div>

WebMVC5/Views/usuario/Inicio.cshtml
@model List<model.entity.usuario>
@{
    ViewBag.Title = "Inicio";
}
<div class="container">
    <div>
        <a class="btn btn-primary" href="~/usuario/create">Nuevo</a>
    </div>
    <div class="row">
        <table class="table">    
         <tr class="btn-primary ">
             <th class="text-center">Codigo</th>
             <th class="text-center">Nombre</th>
             <th class="text-center">Apellido</th>
             <th class="text-center">Telefono</th>
             <th colspan="3" class="text-center">Operaciones</th>
          </tr>
       
    @foreach (var usuario in Model)
            {
           <tr>
            <td>@usuario.Id_user</td>
            <td>@usuario.Nombre</td>
            <td>@usuario.Apellido</td>
            <td>@usuario.Telefono</td> 
               <td><a href="~/usuario/find/@usuario.Id_user" class="btn btn-info">View</a></td>
               <td><a href="~/usuario/create/@usuario.Id_user" class="btn btn-warning">Edit</a></td>
               <td><a href="~/usuario/delete/@usuario.Id_user" class="btn btn-danger">Delete</a></td>
          </tr>
           }
        
        
        </table>
    </div>
</div>

WebMVC5/Views/usuario/Update.cshtml
@model model.dao.usuarioDao
@{
    ViewBag.Title = "Update";
}



<div>
    <h1>@ViewBag.mensajeInicio</h1>
</div>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Id_user, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Id_user, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-actions col-md-offset-2">
            <input class="btn btn-primary" type="submit" name="btnGuardar" value="Guardar" />
            @Html.ActionLink("Regresar al Listado", "Inicio")

        </div>
    </div>
}
<div>
    @ViewBag.mensajeError

</div>